//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheHunt.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Levels : global::System.Configuration.ApplicationSettingsBase {
        
        private static Levels defaultInstance = ((Levels)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Levels())));
        
        public static Levels Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"obstacles\":[{\"x\":3,\"y\":0,\"height\":1,\"width\":1,\"type\":0},{\"x\":3,\"y\":1,\"height\":1" +
            ",\"width\":1,\"type\":0},{\"x\":3,\"y\":2,\"height\":1,\"width\":1,\"type\":0},{\"x\":3,\"y\":3,\"h" +
            "eight\":1,\"width\":1,\"type\":0},{\"x\":3,\"y\":6,\"height\":1,\"width\":1,\"type\":0},{\"x\":0," +
            "\"y\":6,\"height\":1,\"width\":1,\"type\":0},{\"x\":1,\"y\":6,\"height\":1,\"width\":1,\"type\":0}" +
            ",{\"x\":2,\"y\":6,\"height\":1,\"width\":1,\"type\":0},{\"x\":4,\"y\":6,\"height\":1,\"width\":1,\"" +
            "type\":0},{\"x\":5,\"y\":6,\"height\":1,\"width\":1,\"type\":0},{\"x\":6,\"y\":6,\"height\":1,\"wi" +
            "dth\":1,\"type\":0},{\"x\":7,\"y\":6,\"height\":1,\"width\":1,\"type\":0},{\"x\":7,\"y\":5,\"heigh" +
            "t\":1,\"width\":1,\"type\":0},{\"x\":7,\"y\":4,\"height\":1,\"width\":1,\"type\":0},{\"x\":7,\"y\":" +
            "3,\"height\":1,\"width\":1,\"type\":0},{\"x\":14,\"y\":0,\"height\":1,\"width\":1,\"type\":0},{\"" +
            "x\":14,\"y\":1,\"height\":1,\"width\":1,\"type\":0},{\"x\":14,\"y\":2,\"height\":1,\"width\":1,\"t" +
            "ype\":0},{\"x\":14,\"y\":3,\"height\":1,\"width\":1,\"type\":0},{\"x\":14,\"y\":4,\"height\":1,\"w" +
            "idth\":1,\"type\":0},{\"x\":14,\"y\":5,\"height\":1,\"width\":1,\"type\":0},{\"x\":14,\"y\":6,\"he" +
            "ight\":1,\"width\":1,\"type\":0},{\"x\":14,\"y\":7,\"height\":1,\"width\":1,\"type\":0},{\"x\":14" +
            ",\"y\":8,\"height\":1,\"width\":1,\"type\":0},{\"x\":14,\"y\":9,\"height\":1,\"width\":1,\"type\":" +
            "0},{\"x\":14,\"y\":10,\"height\":1,\"width\":1,\"type\":0},{\"x\":14,\"y\":11,\"height\":1,\"widt" +
            "h\":1,\"type\":0},{\"x\":14,\"y\":12,\"height\":1,\"width\":1,\"type\":0},{\"x\":13,\"y\":12,\"hei" +
            "ght\":1,\"width\":1,\"type\":0},{\"x\":12,\"y\":12,\"height\":1,\"width\":1,\"type\":0},{\"x\":11" +
            ",\"y\":12,\"height\":1,\"width\":1,\"type\":0},{\"x\":10,\"y\":12,\"height\":1,\"width\":1,\"type" +
            "\":0},{\"x\":9,\"y\":12,\"height\":1,\"width\":1,\"type\":0},{\"x\":8,\"y\":12,\"height\":1,\"widt" +
            "h\":1,\"type\":0},{\"x\":7,\"y\":12,\"height\":1,\"width\":1,\"type\":0},{\"x\":6,\"y\":12,\"heigh" +
            "t\":1,\"width\":1,\"type\":0},{\"x\":15,\"y\":12,\"height\":1,\"width\":1,\"type\":0},{\"x\":16,\"" +
            "y\":12,\"height\":1,\"width\":1,\"type\":0},{\"x\":17,\"y\":12,\"height\":1,\"width\":1,\"type\":" +
            "0},{\"x\":18,\"y\":12,\"height\":1,\"width\":1,\"type\":0},{\"x\":19,\"y\":12,\"height\":1,\"widt" +
            "h\":1,\"type\":0},{\"x\":20,\"y\":12,\"height\":1,\"width\":1,\"type\":0},{\"x\":21,\"y\":12,\"hei" +
            "ght\":1,\"width\":1,\"type\":0},{\"x\":22,\"y\":12,\"height\":1,\"width\":1,\"type\":0},{\"x\":23" +
            ",\"y\":12,\"height\":1,\"width\":1,\"type\":0},{\"x\":24,\"y\":12,\"height\":1,\"width\":1,\"type" +
            "\":0},{\"x\":25,\"y\":12,\"height\":1,\"width\":1,\"type\":0},{\"x\":26,\"y\":12,\"height\":1,\"wi" +
            "dth\":1,\"type\":0},{\"x\":27,\"y\":12,\"height\":1,\"width\":1,\"type\":0},{\"x\":28,\"y\":12,\"h" +
            "eight\":1,\"width\":1,\"type\":0},{\"x\":29,\"y\":12,\"height\":1,\"width\":1,\"type\":0},{\"x\":" +
            "30,\"y\":12,\"height\":1,\"width\":1,\"type\":0},{\"x\":30,\"y\":11,\"height\":1,\"width\":1,\"ty" +
            "pe\":0},{\"x\":30,\"y\":10,\"height\":1,\"width\":1,\"type\":0},{\"x\":30,\"y\":9,\"height\":1,\"w" +
            "idth\":1,\"type\":0},{\"x\":30,\"y\":8,\"height\":1,\"width\":1,\"type\":0},{\"x\":30,\"y\":7,\"he" +
            "ight\":1,\"width\":1,\"type\":0},{\"x\":30,\"y\":6,\"height\":1,\"width\":1,\"type\":0},{\"x\":39" +
            ",\"y\":6,\"height\":1,\"width\":1,\"type\":0},{\"x\":38,\"y\":6,\"height\":1,\"width\":1,\"type\":" +
            "0},{\"x\":37,\"y\":6,\"height\":1,\"width\":1,\"type\":0},{\"x\":31,\"y\":6,\"height\":1,\"width\"" +
            ":1,\"type\":0},{\"x\":32,\"y\":6,\"height\":1,\"width\":1,\"type\":0},{\"x\":33,\"y\":6,\"height\"" +
            ":1,\"width\":1,\"type\":0},{\"x\":34,\"y\":6,\"height\":1,\"width\":1,\"type\":0},{\"x\":30,\"y\":" +
            "0,\"height\":1,\"width\":1,\"type\":0},{\"x\":30,\"y\":1,\"height\":1,\"width\":1,\"type\":0},{\"" +
            "x\":30,\"y\":2,\"height\":1,\"width\":1,\"type\":0},{\"x\":30,\"y\":5,\"height\":1,\"width\":1,\"t" +
            "ype\":0},{\"x\":22,\"y\":8,\"height\":1,\"width\":1,\"type\":0},{\"x\":21,\"y\":8,\"height\":1,\"w" +
            "idth\":1,\"type\":0},{\"x\":23,\"y\":8,\"height\":1,\"width\":1,\"type\":0},{\"x\":24,\"y\":8,\"he" +
            "ight\":1,\"width\":1,\"type\":0},{\"x\":24,\"y\":7,\"height\":1,\"width\":1,\"type\":0},{\"x\":21" +
            ",\"y\":7,\"height\":1,\"width\":1,\"type\":0}],\"npcs\":[{\"speed\":{\"x\":1,\"y\":1},\"positions" +
            "\":{\"current_position\":{\"x\":10,\"y\":6},\"last_position\":{\"x\":0,\"y\":0}},\"screenSize\"" +
            ":\"1382, 1104\",\"npc\":\"0, 0, 0, 0\",\"sizeBreedte\":34,\"sizeHoogte\":55,\"width\":1,\"hei" +
            "ght\":1,\"type\":2},{\"speed\":{\"x\":1,\"y\":1},\"positions\":{\"current_position\":{\"x\":10," +
            "\"y\":2},\"last_position\":{\"x\":0,\"y\":0}},\"screenSize\":\"1382, 1104\",\"npc\":\"0, 0, 0, " +
            "0\",\"sizeBreedte\":34,\"sizeHoogte\":55,\"width\":1,\"height\":1,\"type\":1},{\"speed\":{\"x\"" +
            ":1,\"y\":1},\"positions\":{\"current_position\":{\"x\":7,\"y\":9},\"last_position\":{\"x\":0,\"" +
            "y\":0}},\"screenSize\":\"1382, 1104\",\"npc\":\"0, 0, 0, 0\",\"sizeBreedte\":34,\"sizeHoogte" +
            "\":55,\"width\":1,\"height\":1,\"type\":0},{\"speed\":{\"x\":1,\"y\":1},\"positions\":{\"current" +
            "_position\":{\"x\":2,\"y\":14},\"last_position\":{\"x\":0,\"y\":0}},\"screenSize\":\"1382, 110" +
            "4\",\"npc\":\"0, 0, 0, 0\",\"sizeBreedte\":34,\"sizeHoogte\":55,\"width\":1,\"height\":1,\"typ" +
            "e\":0},{\"speed\":{\"x\":10,\"y\":10},\"positions\":{\"current_position\":{\"x\":33,\"y\":12},\"" +
            "last_position\":{\"x\":0,\"y\":0}},\"screenSize\":\"1382, 1104\",\"npc\":\"0, 0, 0, 0\",\"size" +
            "Breedte\":34,\"sizeHoogte\":55,\"width\":1,\"height\":1,\"type\":1},{\"speed\":{\"x\":3,\"y\":3" +
            "},\"positions\":{\"current_position\":{\"x\":36,\"y\":2},\"last_position\":{\"x\":0,\"y\":0}}," +
            "\"screenSize\":\"1382, 1104\",\"npc\":\"0, 0, 0, 0\",\"sizeBreedte\":34,\"sizeHoogte\":55,\"w" +
            "idth\":1,\"height\":1,\"type\":0},{\"speed\":{\"x\":5,\"y\":5},\"positions\":{\"current_positi" +
            "on\":{\"x\":34,\"y\":16},\"last_position\":{\"x\":0,\"y\":0}},\"screenSize\":\"1382, 1104\",\"np" +
            "c\":\"0, 0, 0, 0\",\"sizeBreedte\":34,\"sizeHoogte\":55,\"width\":1,\"height\":1,\"type\":0}," +
            "{\"speed\":{\"x\":10,\"y\":10},\"positions\":{\"current_position\":{\"x\":23,\"y\":16},\"last_p" +
            "osition\":{\"x\":0,\"y\":0}},\"screenSize\":\"1382, 1104\",\"npc\":\"0, 0, 0, 0\",\"sizeBreedt" +
            "e\":34,\"sizeHoogte\":55,\"width\":1,\"height\":1,\"type\":0},{\"speed\":{\"x\":0,\"y\":0},\"pos" +
            "itions\":{\"current_position\":{\"x\":27,\"y\":10},\"last_position\":{\"x\":0,\"y\":0}},\"scre" +
            "enSize\":\"1382, 1104\",\"npc\":\"0, 0, 0, 0\",\"sizeBreedte\":34,\"sizeHoogte\":55,\"width\"" +
            ":1,\"height\":1,\"type\":0},{\"speed\":{\"x\":0,\"y\":0},\"positions\":{\"current_position\":{" +
            "\"x\":17,\"y\":10},\"last_position\":{\"x\":0,\"y\":0}},\"screenSize\":\"1382, 1104\",\"npc\":\"0" +
            ", 0, 0, 0\",\"sizeBreedte\":34,\"sizeHoogte\":55,\"width\":1,\"height\":1,\"type\":0},{\"spe" +
            "ed\":{\"x\":0,\"y\":0},\"positions\":{\"current_position\":{\"x\":17,\"y\":1},\"last_position\"" +
            ":{\"x\":0,\"y\":0}},\"screenSize\":\"1382, 1104\",\"npc\":\"0, 0, 0, 0\",\"sizeBreedte\":34,\"s" +
            "izeHoogte\":55,\"width\":1,\"height\":1,\"type\":0},{\"speed\":{\"x\":0,\"y\":0},\"positions\":" +
            "{\"current_position\":{\"x\":27,\"y\":1},\"last_position\":{\"x\":0,\"y\":0}},\"screenSize\":\"" +
            "1382, 1104\",\"npc\":\"0, 0, 0, 0\",\"sizeBreedte\":34,\"sizeHoogte\":55,\"width\":1,\"heigh" +
            "t\":1,\"type\":0},{\"speed\":{\"x\":1,\"y\":1},\"positions\":{\"current_position\":{\"x\":34,\"y" +
            "\":11},\"last_position\":{\"x\":0,\"y\":0}},\"screenSize\":\"1382, 1104\",\"npc\":\"0, 0, 0, 0" +
            "\",\"sizeBreedte\":34,\"sizeHoogte\":55,\"width\":1,\"height\":1,\"type\":1},{\"speed\":{\"x\":" +
            "1,\"y\":1},\"positions\":{\"current_position\":{\"x\":35,\"y\":10},\"last_position\":{\"x\":0," +
            "\"y\":0}},\"screenSize\":\"1382, 1104\",\"npc\":\"0, 0, 0, 0\",\"sizeBreedte\":34,\"sizeHoogt" +
            "e\":55,\"width\":1,\"height\":1,\"type\":1},{\"speed\":{\"x\":1,\"y\":1},\"positions\":{\"curren" +
            "t_position\":{\"x\":36,\"y\":9},\"last_position\":{\"x\":0,\"y\":0}},\"screenSize\":\"1382, 11" +
            "04\",\"npc\":\"0, 0, 0, 0\",\"sizeBreedte\":34,\"sizeHoogte\":55,\"width\":1,\"height\":1,\"ty" +
            "pe\":1},{\"speed\":{\"x\":1,\"y\":1},\"positions\":{\"current_position\":{\"x\":37,\"y\":8},\"la" +
            "st_position\":{\"x\":0,\"y\":0}},\"screenSize\":\"1382, 1104\",\"npc\":\"0, 0, 0, 0\",\"sizeBr" +
            "eedte\":34,\"sizeHoogte\":55,\"width\":1,\"height\":1,\"type\":1},{\"speed\":{\"x\":1,\"y\":1}," +
            "\"positions\":{\"current_position\":{\"x\":38,\"y\":7},\"last_position\":{\"x\":0,\"y\":0}},\"s" +
            "creenSize\":\"1382, 1104\",\"npc\":\"0, 0, 0, 0\",\"sizeBreedte\":34,\"sizeHoogte\":55,\"wid" +
            "th\":1,\"height\":1,\"type\":1},{\"speed\":{\"x\":3,\"y\":3},\"positions\":{\"current_position" +
            "\":{\"x\":21,\"y\":14},\"last_position\":{\"x\":0,\"y\":0}},\"screenSize\":\"1382, 1104\",\"npc\"" +
            ":\"0, 0, 0, 0\",\"sizeBreedte\":34,\"sizeHoogte\":55,\"width\":1,\"height\":1,\"type\":2},{\"" +
            "speed\":{\"x\":3,\"y\":3},\"positions\":{\"current_position\":{\"x\":20,\"y\":15},\"last_posit" +
            "ion\":{\"x\":0,\"y\":0}},\"screenSize\":\"1382, 1104\",\"npc\":\"0, 0, 0, 0\",\"sizeBreedte\":3" +
            "4,\"sizeHoogte\":55,\"width\":1,\"height\":1,\"type\":2},{\"speed\":{\"x\":3,\"y\":3},\"positio" +
            "ns\":{\"current_position\":{\"x\":19,\"y\":16},\"last_position\":{\"x\":0,\"y\":0}},\"screenSi" +
            "ze\":\"1382, 1104\",\"npc\":\"0, 0, 0, 0\",\"sizeBreedte\":34,\"sizeHoogte\":55,\"width\":1,\"" +
            "height\":1,\"type\":2},{\"speed\":{\"x\":3,\"y\":3},\"positions\":{\"current_position\":{\"x\":" +
            "18,\"y\":17},\"last_position\":{\"x\":0,\"y\":0}},\"screenSize\":\"1382, 1104\",\"npc\":\"0, 0," +
            " 0, 0\",\"sizeBreedte\":34,\"sizeHoogte\":55,\"width\":1,\"height\":1,\"type\":2},{\"speed\":" +
            "{\"x\":3,\"y\":3},\"positions\":{\"current_position\":{\"x\":17,\"y\":18},\"last_position\":{\"" +
            "x\":0,\"y\":0}},\"screenSize\":\"1382, 1104\",\"npc\":\"0, 0, 0, 0\",\"sizeBreedte\":34,\"size" +
            "Hoogte\":55,\"width\":1,\"height\":1,\"type\":2},{\"speed\":{\"x\":3,\"y\":3},\"positions\":{\"c" +
            "urrent_position\":{\"x\":16,\"y\":19},\"last_position\":{\"x\":0,\"y\":0}},\"screenSize\":\"13" +
            "82, 1104\",\"npc\":\"0, 0, 0, 0\",\"sizeBreedte\":34,\"sizeHoogte\":55,\"width\":1,\"height\"" +
            ":1,\"type\":2},{\"speed\":{\"x\":3,\"y\":3},\"positions\":{\"current_position\":{\"x\":22,\"y\":" +
            "13},\"last_position\":{\"x\":0,\"y\":0}},\"screenSize\":\"1382, 1104\",\"npc\":\"0, 0, 0, 0\"," +
            "\"sizeBreedte\":34,\"sizeHoogte\":55,\"width\":1,\"height\":1,\"type\":2},{\"speed\":{\"x\":3," +
            "\"y\":3},\"positions\":{\"current_position\":{\"x\":3,\"y\":12},\"last_position\":{\"x\":0,\"y\"" +
            ":0}},\"screenSize\":\"1382, 1104\",\"npc\":\"0, 0, 0, 0\",\"sizeBreedte\":34,\"sizeHoogte\":" +
            "55,\"width\":1,\"height\":1,\"type\":1}],\"player\":{\"img\":null,\"positions\":{\"current_po" +
            "sition\":{\"x\":1,\"y\":1},\"last_position\":{\"x\":0,\"y\":0}},\"speed\":{\"x\":3,\"y\":3},\"move" +
            "ment\":{\"walk\":{\"x\":3,\"y\":3},\"run\":{\"x\":5,\"y\":5}},\"sizeBreedte\":34,\"sizeHoogte\":5" +
            "5},\"boss\":{\"position\":{\"x\":0,\"y\":0},\"speed\":{\"x\":0,\"y\":0},\"movement\":{\"walk\":{\"x" +
            "\":0,\"y\":0},\"run\":{\"x\":0,\"y\":0}},\"sizeBreedte\":54,\"sizeHoogte\":72}}")]
        public string level1 {
            get {
                return ((string)(this["level1"]));
            }
            set {
                this["level1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string level2 {
            get {
                return ((string)(this["level2"]));
            }
            set {
                this["level2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string level3 {
            get {
                return ((string)(this["level3"]));
            }
            set {
                this["level3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string level4 {
            get {
                return ((string)(this["level4"]));
            }
            set {
                this["level4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string level5 {
            get {
                return ((string)(this["level5"]));
            }
            set {
                this["level5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string customlv2 {
            get {
                return ((string)(this["customlv2"]));
            }
            set {
                this["customlv2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string customlv3 {
            get {
                return ((string)(this["customlv3"]));
            }
            set {
                this["customlv3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string customlv4 {
            get {
                return ((string)(this["customlv4"]));
            }
            set {
                this["customlv4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string customlv5 {
            get {
                return ((string)(this["customlv5"]));
            }
            set {
                this["customlv5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string customlv6 {
            get {
                return ((string)(this["customlv6"]));
            }
            set {
                this["customlv6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string customlv7 {
            get {
                return ((string)(this["customlv7"]));
            }
            set {
                this["customlv7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string customlv8 {
            get {
                return ((string)(this["customlv8"]));
            }
            set {
                this["customlv8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string customlv9 {
            get {
                return ((string)(this["customlv9"]));
            }
            set {
                this["customlv9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string customlv10 {
            get {
                return ((string)(this["customlv10"]));
            }
            set {
                this["customlv10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string customlv1 {
            get {
                return ((string)(this["customlv1"]));
            }
            set {
                this["customlv1"] = value;
            }
        }
    }
}
