//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheHunt.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Levels : global::System.Configuration.ApplicationSettingsBase {
        
        private static Levels defaultInstance = ((Levels)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Levels())));
        
        public static Levels Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\r\n  \"obstacles\": [\r\n    {\r\n      \"x\": 5,\r\n      \"y\": 5\r\n    },\r\n    {\r\n      \"x\"" +
            ": 10,\r\n      \"y\": 10\r\n    }\r\n  ],\r\n  \"boss\": {\r\n    \"position\": {\r\n      \"x\": 50" +
            "0,\r\n      \"y\": 500\r\n    },\r\n        \"speed\": {\r\n      \"x\": 3,\r\n      \"y\": 3\r\n   " +
            " },\r\n    \"movement\": {\r\n       \"walk\": {\r\n        \"x\": 3,\r\n        \"y\": 3\r\n     " +
            " },\r\n      \"run\": {\r\n        \"x\": 10,\r\n        \"y\": 10\r\n      }\r\n    },\r\n    \"hp" +
            "\": 100\r\n  },\r\n  \"npcs\": [\r\n    {\r\n      \"type\": \"Enemy\",\r\n      \"positions\": {\r\n" +
            "        \"current_position\": {\r\n          \"x\": 300,\r\n          \"y\": 300\r\n        " +
            "},\r\n        \"return_position\": {\r\n          \"x\": 70,\r\n          \"y\": 20\r\n       " +
            " }\r\n      },\r\n      \"speed\": {\r\n        \"x\": 5,\r\n        \"y\": 5\r\n      }\r\n    }," +
            "\r\n    {\r\n      \"type\": \"Enemy\",\r\n      \"positions\": {\r\n        \"current_position" +
            "\": {\r\n          \"x\": 150,\r\n          \"y\": 50\r\n        },\r\n        \"return_positi" +
            "on\": {\r\n          \"x\": 70,\r\n          \"y\": 20\r\n        }\r\n      },\r\n      \"speed" +
            "\": {\r\n        \"x\": 4,\r\n        \"y\": 4\r\n      }\r\n    },\r\n    {\r\n      \"type\": \"En" +
            "emy\",\r\n      \"positions\": {\r\n        \"current_position\": {\r\n          \"x\": 500,\r" +
            "\n          \"y\": 350\r\n        },\r\n        \"return_position\": {\r\n          \"x\": 70" +
            ",\r\n          \"y\": 20\r\n        }\r\n      },\r\n      \"speed\": {\r\n        \"x\": 3,\r\n  " +
            "      \"y\": 3\r\n      }\r\n    },\r\n    {\r\n      \"type\": \"Enemy\",\r\n      \"positions\":" +
            " {\r\n        \"current_position\": {\r\n          \"x\": 500,\r\n          \"y\": 100\r\n    " +
            "    },\r\n        \"return_position\": {\r\n          \"x\": 70,\r\n          \"y\": 20\r\n   " +
            "     }\r\n      },\r\n      \"speed\": {\r\n        \"x\": 2,\r\n        \"y\": 2\r\n      }\r\n  " +
            "  },\r\n    {\r\n      \"type\": \"Enemy\",\r\n      \"positions\": {\r\n        \"current_posi" +
            "tion\": {\r\n          \"x\": 700,\r\n          \"y\": 150\r\n        },\r\n        \"return_p" +
            "osition\": {\r\n          \"x\": 70,\r\n          \"y\": 20\r\n        }\r\n      },\r\n      \"" +
            "speed\": {\r\n        \"x\": 1,\r\n        \"y\": 1\r\n      }\r\n    },\r\n  ],\r\n  \"player\": {" +
            "\r\n    \"img\": \"ww1\",\r\n    \"positions\": {\r\n      \"current_position\": {\r\n        \"x" +
            "\": 0,\r\n        \"y\": 300\r\n      },\r\n      \"last_position\": {\r\n        \"x\": 0,\r\n  " +
            "      \"y\": 300\r\n      }\r\n    },\r\n    \"speed\": {\r\n      \"x\": 3,\r\n      \"y\": 3\r\n  " +
            "  },\r\n    \"movement\": {\r\n      \"walk\": {\r\n        \"x\": 2,\r\n        \"y\": 2\r\n     " +
            " },\r\n      \"run\": {\r\n        \"x\": 5,\r\n        \"y\": 5\r\n      }\r\n    }\r\n\r\n  }\r\n  }" +
            "\r\n")]
        public string level1 {
            get {
                return ((string)(this["level1"]));
            }
            set {
                this["level1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string level2 {
            get {
                return ((string)(this["level2"]));
            }
            set {
                this["level2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string level3 {
            get {
                return ((string)(this["level3"]));
            }
            set {
                this["level3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string level4 {
            get {
                return ((string)(this["level4"]));
            }
            set {
                this["level4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string level5 {
            get {
                return ((string)(this["level5"]));
            }
            set {
                this["level5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string customlv2 {
            get {
                return ((string)(this["customlv2"]));
            }
            set {
                this["customlv2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string customlv3 {
            get {
                return ((string)(this["customlv3"]));
            }
            set {
                this["customlv3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string customlv4 {
            get {
                return ((string)(this["customlv4"]));
            }
            set {
                this["customlv4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string customlv5 {
            get {
                return ((string)(this["customlv5"]));
            }
            set {
                this["customlv5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string customlv6 {
            get {
                return ((string)(this["customlv6"]));
            }
            set {
                this["customlv6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string customlv7 {
            get {
                return ((string)(this["customlv7"]));
            }
            set {
                this["customlv7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string customlv8 {
            get {
                return ((string)(this["customlv8"]));
            }
            set {
                this["customlv8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string customlv9 {
            get {
                return ((string)(this["customlv9"]));
            }
            set {
                this["customlv9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string customlv10 {
            get {
                return ((string)(this["customlv10"]));
            }
            set {
                this["customlv10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string customlv1 {
            get {
                return ((string)(this["customlv1"]));
            }
            set {
                this["customlv1"] = value;
            }
        }
    }
}
